### PR TITLE
Precompiled embed wraps are now optional with lazy modules the default

### PR DESCRIPTION
**Pull request by nerfZael**

### CODE REVIEW

**Review by krisbitney — APPROVED** [review]
LGTM!

**Comment by cbrzn** [comment]
hey @krisbitney can u please test this version in kotlin to see if it solves your problem?

**Comment by krisbitney** [comment]
> hey @krisbitney can u please test this version in kotlin to see if it solves your problem?

Yes, for sure, good idea. I'll report my findings very soon!

**Comment by krisbitney** [comment]
This PR did fix the Android problem

**Pull request merged**
